# Generated by Django 4.1 on 2022-08-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('detalhevenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhevenda',
            old_name='qtd_produto',
            new_name='quantidade_produto',
        ),
        migrations.AlterField(
            model_name='detalhevenda',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
