# Generated by Django 4.1 on 2022-08-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalhevenda', '0003_rename_cod_venda_detalhevenda_codigo_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhevenda',
            old_name='codigo_venda',
            new_name='cod_venda',
        ),
    ]
