# Generated by Django 4.1 on 2022-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('detalhevenda', '0004_rename_codigo_venda_detalhevenda_cod_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhevenda',
            name='cod_produto',
        ),
        migrations.AddField(
            model_name='detalhevenda',
            name='cod_produto',
            field=models.ManyToManyField(to='produtos.produto'),
        ),
    ]
