# Generated by Django 4.1 on 2022-08-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_cod_venda'),
        ('detalhevenda', '0006_remove_detalhevenda_cod_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhevenda',
            name='id',
        ),
        migrations.AlterField(
            model_name='detalhevenda',
            name='cod_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendas.venda'),
        ),
    ]
