# Generated by Django 4.1 on 2022-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.CharField(max_length=1)),
            ],
        ),
    ]
